name: CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install and Build 🔧
        run: |
          npm install
          npm run build

      - name: Copy build files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          strip_components: 3
          source: '/home/runner/work/hoolicash-admin/hoolicash-admin/build/'
          target: 'morethan/hoolicash-admin/build'

      - name: Restart server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd morethan
            docker-compose rm --stop hoolicash-admin
            docker-compose up --detach --build hoolicash-admin
